name: apicuron-on-commit
description: This action will report to APICURON on every push
author: Unipd

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  REPORT_API_ENDPOINT:
    description: 'Endpoint for sending final reports'
    required: true
  REPORT_API_TOKEN:
    description: 'Authentication token for report API'
    required: false
  USER_INFO_SERVICE_ENDPOINT:
    description: 'Endpoint for user information lookup'
    required: true
  USER_INFO_SERVICE_TOKEN:
    description: 'Authentication token for user info service'
    required: false
  RESOURCE_ID:
    description: 'Identifier of the resource in APICURON'
    required: true
  RESOURCE_URL:
    description: 'URL of the repository'
    required: false
  ACTIVITY_NAME:
    description: 'APICURON Activity name to be reported'
    required: true
  LEAGUE:
    description: 'APICURON League associated with the committer'
    default: 'default'
    required: true
# Define your outputs here.
outputs:
  reports:
    description: JSON array of activity logs

runs:
  using: node20
  main: dist/index.js
